server:
  port: 8090
spring:
  datasource:
    url: jdbc:mysql://db.ctd.academy:3306/pi21023c01_GRUPO2
    username: pi21023c01_GRUPO2
    password: neoQuei3
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    properties:
      generate-ddl: ture
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
        ddl-auto: update
  security:
    oauht2:
      client:
        provider:
          keycloak:
            token-uri: http://localhost:8080/realms/eventos/protocol/openid-connect/token
        registration:
          keycloak:
            authorizationGrantType: client_credentials
            client-id: users-client
            client-secret: users-secret

dh:
  keycloak:
    serverUrl: http://localhost:8080/
    realm: eventos
    username: ${KEYCLOAK_USER:admin}
    password: ${KEYCLOAK_PASSWORD:admin}
    clientId: admin-cli
