name: Backend
run-name: ¡Desplegando Backend!

on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'zulu'
        cache: maven
    - name: Cache Maven
      id: cache-primes
      uses: actions/cache@v3
      with:
          path: |
            ~/.m2
            ~/repository
          key: ${{ github.job }}-${{ hashFiles('**/pom.xml') }}
  
    - name: Build with Maven
      run: mvn -B package --file /home/ubuntu/actions-runner/_work/Proyecto-Integrador/Proyecto-Integrador/pom.xml
    - name: Execute Jar File
      run: sudo kill -9 `sudo lsof -t -i:80` & sudo java -jar /home/ubuntu/actions-runner/_work/Proyecto-Integrador/Proyecto-Integrador/target/evently-0.0.1-SNAPSHOT.jar &
