name: Backend
run-name: ¡Desplegando Backend!

on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        cache: maven
        distribution: 'temurin'
    - name: Clean with Maven
      run: mvn -B clean --file /home/ubuntu/actions-runner/_work/Proyecto-Integrador/Proyecto-Integrador/pom.xml
    - name: Validate with Maven
      run: mvn -B validate --file /home/ubuntu/actions-runner/_work/Proyecto-Integrador/Proyecto-Integrador/pom.xml
    - name: Compile with Maven
      run: mvn -B compile --file /home/ubuntu/actions-runner/_work/Proyecto-Integrador/Proyecto-Integrador/pom.xml
    - name: Build with Maven
      run: mvn -B package --file /home/ubuntu/actions-runner/_work/Proyecto-Integrador/Proyecto-Integrador/pom.xml
    - name: Execute Jar File
      run: sudo kill -9 `sudo lsof -t -i:80` & sudo java -jar /home/ubuntu/actions-runner/_work/Proyecto-Integrador/Proyecto-Integrador/target/evently-0.0.1-SNAPSHOT.jar &
